# Generated by Django 4.1.13 on 2025-02-27 04:54

import apps.call_analyzer.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=apps.call_analyzer.models.call_recording_path)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('call_date', models.DateField(blank=True, null=True)),
                ('call_type', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_company', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_recordings', to='core.organization')),
                ('tags', models.ManyToManyField(blank=True, related_name='call_recordings', to='core.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('segments', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('call_recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='call_analyzer.callrecording')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_sentiment', models.CharField(max_length=20)),
                ('overall_score', models.FloatField()),
                ('segment_sentiment', models.JSONField(default=list)),
                ('emotions', models.JSONField(default=dict)),
                ('call_recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='call_analyzer.callrecording')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('talk_ratio', models.FloatField(blank=True, null=True)),
                ('interruption_count', models.IntegerField(default=0)),
                ('avg_response_time', models.DurationField(blank=True, null=True)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('call_recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='call_analyzer.callrecording')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overview', models.TextField()),
                ('key_points', models.JSONField(default=list)),
                ('action_items', models.JSONField(default=list)),
                ('questions', models.JSONField(default=list)),
                ('objections', models.JSONField(default=list)),
                ('call_recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='call_analyzer.callrecording')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
