# Generated by Django 4.1.13 on 2025-02-27 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='call_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='sentiment_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callsummary',
            name='summary_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callsummary',
            name='call_recording',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_summary_detail', to='call_analyzer.callrecording'),
        ),
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='call_recording',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analysis', to='call_analyzer.callrecording'),
        ),
    ]
