# Generated by Django 4.1.13 on 2025-02-27 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_analyzer', '0002_callrecording_call_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrecording',
            name='call_summary',
        ),
        migrations.RemoveField(
            model_name='callrecording',
            name='sentiment_data',
        ),
        migrations.RemoveField(
            model_name='callrecording',
            name='transcript',
        ),
        migrations.RemoveField(
            model_name='callsummary',
            name='summary_text',
        ),
        migrations.AlterField(
            model_name='callsummary',
            name='call_recording',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='call_analyzer.callrecording'),
        ),
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='call_recording',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='call_analyzer.callrecording'),
        ),
    ]
